dist: bionic

language: php

php:
  - 7.4
  - 7.3
  - 7.2

before_install:
  - composer self-update
  
install:
  - composer install --prefer-dist

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit tests --coverage-clover build/logs/clover.xml

before_install:
  - sudo apt-get update
  - sudo apt-get -y install tesseract-ocr

after_success:
  - travis_retry php vendor/bin/php-coveralls

