---  
- name: Update repository PHP OCR
  hosts: criare
  tasks:
    - name: PHP OCR Github Repository
      become: yes
      git:
        repo: 'git@github.com:rafaeldemeirateixeira/ci.git'
        dest: "/var/www/phpocr"