name: PHP CI and CD

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Update Ubuntu
      run: sudo apt-get update
    
    - name: Tesseract OCR
      run: sudo apt-get -y install tesseract-ocr

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Create log directory
      run: mkdir -p build/logs
      
    - name: Run test suite
      run: composer ci

    - name: Action - Deployer php
      uses: musps/action-deployer-php@v0.0.2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

